language: python
sudo: false
cache: pip

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0"

  matrix:
  - LINT_CHECK="1"
  # `web_gantt_public_holidays` depends on `web_gantt@enterprise`, thus can't be tested
  - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="web_gantt_public_holidays"
  - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="web_gantt_public_holidays"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
- travis_after_tests_success
